# Generated by Django 3.2.3 on 2021-07-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('sky_condition', models.CharField(choices=[('SKC', 'Clear skies'), ('FEW', 'Few clouds'), ('SCT', 'Scattered clouds'), ('BKN', 'Broken'), ('OVC', 'Overcast')], max_length=3)),
                ('wind_dir', models.CharField(choices=[('NAN', 'No wind'), ('000', 'North'), ('045', 'Northeast'), ('090', 'East'), ('135', 'Southeast'), ('180', 'South'), ('225', 'Southwest'), ('270', 'West'), ('315', 'Northwest')], max_length=3)),
                ('wind_vel', models.FloatField(default=0)),
                ('temp', models.FloatField()),
            ],
        ),
    ]
