# Generated by Django 3.2.3 on 2021-07-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traccapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherreport',
            name='wind_vel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
