# Generated by Django 3.2.3 on 2021-07-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traccapp', '0004_alter_weatherreport_wind_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherreport',
            name='wind_vel',
            field=models.FloatField(default=0),
        ),
    ]
